### ISSUE TITLE
Agular not compatable facing below issues

### ISSUE THREAD

**Issue by chenchuraviteja** [adminkit/adminkit#114] opened 2021-09-30 08:15 UTC
Angular version facing issues Uncaught SyntaxError: Cannot use import statement outside a module
![Screenshot from 2021-09-30 13-44-01](https://user-images.githubusercontent.com/33121914/135414259-0d1899da-564c-4c5a-824a-c8ee70d276d1.png)
![Screenshot from 2021-09-30 13-44-21](https://user-images.githubusercontent.com/33121914/135414273-25bbd857-65f8-4b21-992e-cba7beb7ce18.png)
![Screenshot from 2021-09-30 13-44-42](https://user-images.githubusercontent.com/33121914/135414283-5ccdf5af-2089-485f-87c9-3299945ba73c.png)

**Comment by paullaros** [comment] 2021-09-30 10:25
This open source library is not built for Angular, nor states that the Angular framework is supported. Closing this issue as this is not a bug, and we don't have immediate plans to add an Angular version. Feel free to fork the project and convert it to Angular.

**Comment by paullaros** [comment] 2021-09-30 10:26
This open source library is not built for Angular, nor states that the Angular framework is supported. Closing this issue as this is not a bug, and we don't have immediate plans to add an Angular version.

**Closed by paullaros** 2021-09-30 10:25 UTC
